# This is a sample config file for the etl process

spark:
  appname: dataverse_etl_sample
  driver:
    memory: 16g
etl:
  - name: data_ingestion___parquet___pq2ufl
    args:
      path:
        - ./sample/preprocess_ufl.parquet
  - name: data_load___huggingface___ufl2hf_obj
