name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]

body:
  - type: textarea
    id: environment-setting
    attributes:
      label: "Environment Settings"
      description: Java, Pyspark version, Python version, ...
      placeholder: Let us explain your environment settings to reproduce
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      placeholder: A clear and concise description of what you would expect to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      placeholder: A clear and concise description of what actually happened.
      
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Please enter an explicit steps to reproduce your problem.
        If you have any code snippets, error messages, and etc., please provide them here.

      placeholder: |
        Steps to reproduce:
          
          1.
          2.
          3.
          4.
    validations:
      required: true


